### ISSUE TITLE
Config files aren't updated by copy/code/down

### ISSUE THREAD

**Issue by KarlBishop** [fortrabbit/craft-copy#109]
After changing Settings on a remote environment - such as re-ordering Sites in a Site Group or editing Permissions of a User Group - they are not updated on my local environment when I run `copy/code/down` (or `copy/db/down`).

When I make similar changes on the local environment they are reflected in the config folder and I can push them to the remote by running `copy/code/up`.

I think `copy/code/down` should mirror the behaviour of `copy/code/up` so that config changes can be propagated in either direction - is that not correct?

### Notes

Craft Pro 3.6.12
Copy 1.0.4

Remote:
PHP: 7.4.15
MySQL: 8.0.20

Local:
PHP: 7.4.16
MySQL: 8.0.23

I tried running **Project Config > Rebuild** on the remote before copying down.

The output from `copy/code/down` says "Already up to date."

I know I should switch off `allowAdminChanges` and `allowUpdates` on the remote before putting the site live but it's useful whilst developing to have these enabled.

**Comment by frank-laemmer** [comment]
I think this is expected behavior. 

You write: _After changing Settings on a remote environment._ - I guess you did so either by clicking around in the Craft Control Panel or by changing files on the file system on the App itself while being logged in by SSH. Either way, that might have changed the `project.yml` files on the App itself and you want these changes to be reflected in your development environment as well?

Changes on the file system are not being back ported to Git. Git on fortrabbit is a one way street:

```
local code   >   fortrabbit deploy service  >  fortrabbit App
```

More [details here](https://help.fortrabbit.com/deployment-methods-uni#toc-git-works-only-one-way).

That's actually why we suggest to switch off `allowAdminChanges` and `allowUpdates` on the remote App. So there is no solution to your workflow.

I hope I was poking in the right direction?

**Comment by KarlBishop** [comment]
Ahh, OK I see.

I was confused because in the [readme](https://github.com/fortrabbit/craft-copy#code) it says `copy/code/down` will "Pull code changes from your fortrabbit App". But if Git is a one way street, then I guess that means `copy/code/down` isn't really useful for a 1:1 remote and local environment setup (apart from to initialise a new local environment from an existing remote). Is that right?

**Comment by frank-laemmer** [comment]
Kinda. We suggest that you do code changes only in your local development environment and that all your code is in Git. So there are no code changes and no configuration changes on the App itself happening. That is by design.

`copy/code/down` will do a `git pull` basically. You will need that when you are collaborating with other on the same code base. Otherwise, when working alone on the code base, you will only push code changes up.

Craft Copy helps me mostly to sync the assets and copy the database.
