### ISSUE TITLE
copy/volumes/up rsync error

### ISSUE THREAD

**Issue by turnstylerj** [fortrabbit/craft-copy#125]
## Description

Running `php craft copy/volumes/up` (for the first time) is resulting in the following output:

```
Rsync started
-------------

building file list ... done

–––––––––––––––––––––––  ∙ƒ  –––––––––––––––––––––––


A B O R T E D

  !! Command exited with non-zero result.

rsync: connection unexpectedly closed (8 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /System/Volumes/Data/SWE/macOS/BuildRoots/38cf1d983f/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/io.c(453) [sender=2.6.9]


All done.
```

`copy/code` and `copy/db` are working as expectedly.

## Additional Info
Craft CMS version: `3.7.17`
craft-copy version: `1.0.7`

**Comment by brycekirk** [comment]
I'm hitting this exact error, with a slightly different path:

`rsync error: error in rsync protocol data stream (code 12) at /AppleInternal/Library/BuildRoots/810eba08-405a-11ed-86e9-6af958a02716/Library/Caches/com.apple.xbs/Sources/rsync/rsync/io.c(453) [sender=2.6.9]`

It seems to be related to the fortrabbit environment, since `./craft copy/volumes/up` is working on all my other fortrabbit websites.

**Comment by brycekirk** [comment]
Was able to fix this by SSHing into the app and making the directories. In my case:
`mkdir web/assets/uploads`
`mkdir web/assets/uploads/img`

**Comment by pheeque1** [comment]
Hi @brycekirk,

It looks like this might be due to how the command is used or the app in question. We might need logs from you to debug further. 

For privacy, this is better discussed in the official fortrabbit support channel. 
Please open a ticket with the chat bubble in the Dashboard.
