### ISSUE TITLE
Make Craft Automigrate a setup setting 

### ISSUE THREAD

**Issue by frank-laemmer** [fortrabbit/craft-copy#57]
Craft Copy uses [Craft Automigrate](https://github.com/fortrabbit/craft-auto-migrate). This may come as a surprise for some users. So it would be nice to give it some visibility when using the tool. Therefore I can imagine that there is a question on `craft copy/setup`.

```
Enable Craft Automigrate? [Yes]
Will run database migrations each time you'll deploy.
```

**Comment by ostark** [comment]
Since [fortrabbit/craft-auto-migrate](https://github.com/fortrabbit/craft-auto-migrate) is a composer plugin, Craft Copy can not control its behavior directly.

I can imagine a dialog like this

*Enable Craft Automigrate? [Yes]*

**Yes** -> does nothing
**No** -> shows instructions how to set the Env var on fortrabbit
```
DISABLE_CRAFT_AUTOMIGRATE=1
```

**Comment by frank-laemmer** [comment]
Current status:

- [x] Better documentation on the feature in README
- [ ] Discussion and decision on how to proceed

**Comment by ostark** [comment]
Since this is essential for the Composer / Project Config workflow, the need for disabling it an edge case.
I'd prefer fewer options and dialogs.
